# Generated by Django 5.1.2 on 2024-11-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True  # First Miagration for this App

    dependencies = [
    ]

    # operations: record what you change on Model which need to change on DB also
    operations = [ 
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=20)),
                ('post_content', models.TextField()),
                ('publised_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
